# use Docker-based container (instead of OpenVZ)
sudo: false

language: scala

scala:
  - 2.11.6
  - 2.10.5

jdk:
  - openjdk6
  - oraclejdk7
  - oraclejdk8

script: sbt ++$TRAVIS_SCALA_VERSION test

notifications:
  email:
    - r.m.deak@gmail.com
